const $=id=>document.getElementById(id), q=(s,r=document)=>r.querySelector(s);
const tasks=[['01','Random Walk'],['02','Brownian Motion'],['03','Black Bodies & Heat'],['04','Photoelectric Effect'],['05','Hydrogen · The Quantised Atom'],['06','Electron Diffraction'],['07','Particle in a Box'],['08','Quantum Cryptography'],['09','Compton Scattering'],['10','Hydrogenic Orbitals']];
$('taskNav').innerHTML=tasks.map((t,i)=>`<a class="nav-item ${i===0?'active':''}" href="#task${i+1}"><span class="nav-num">${t[0]}</span><span>${t[1]}</span></a>`).join('');
const nav=[...document.querySelectorAll('.nav-item')], sections=[...document.querySelectorAll('.exhibit')];
const observer=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){const n=e.target.dataset.task;nav.forEach(x=>x.classList.toggle('active',x.getAttribute('href')===`#task${n}`));$('progressLabel').textContent=`${String(n).padStart(2,'0')} / 10`;}})},{rootMargin:'-25% 0px -65% 0px'});sections.forEach(s=>observer.observe(s));
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.getElementById('task'+b.dataset.go)?.scrollIntoView({behavior:'smooth'}));
$('themeBtn').onclick=()=>document.documentElement.classList.toggle('light');
function setupCanvas(c){const dpr=devicePixelRatio||1, r=c.getBoundingClientRect();c.width=Math.max(300,r.width*dpr);c.height=Math.max(300,r.height*dpr);const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);return x}
function axes(ctx,w,h,x0,y0,x1,y1){ctx.strokeStyle='#273039';ctx.lineWidth=1;ctx.strokeRect(x0,y0,x1-x0,y1-y0);}
function clear(ctx,w,h){ctx.fillStyle='#0b0f13';ctx.fillRect(0,0,w,h)}
// Task 1
let seed1=42;
function rng(){seed1=(1664525*seed1+1013904223)>>>0;return seed1/4294967296}
function draw1(){const c=$('canvas1'),ctx=setupCanvas(c),w=c.clientWidth,h=c.clientHeight,N=+$('n1').value,s=+$('s1').value,W=+$('w1').value;clear(ctx,w,h);let all=[],max=1,sum=0;for(let k=0;k<W;k++){let x=0,y=0,p=[[0,0]];for(let i=0;i<N;i++){let a=rng()*Math.PI*2;x+=s*Math.cos(a);y+=s*Math.sin(a);p.push([x,y])}all.push(p);sum+=x*x+y*y;max=Math.max(max,...p.map(z=>Math.hypot(z[0],z[1])))}let scale=.42*Math.min(w,h)/max;ctx.save();ctx.translate(w/2,h/2);all.forEach((p,k)=>{ctx.beginPath();p.forEach((z,i)=>i?ctx.lineTo(z[0]*scale,-z[1]*scale):ctx.moveTo(z[0]*scale,-z[1]*scale));ctx.strokeStyle=`hsl(${95+k*11} 65% ${55+k%3*8}%)`;ctx.globalAlpha=.72;ctx.lineWidth=1.1;ctx.stroke()});ctx.fillStyle='#c8ff5a';ctx.beginPath();ctx.arc(0,0,4,0,7);ctx.fill();ctx.restore();let rms=Math.sqrt(sum/W);$('rms1').textContent=rms.toFixed(2);$('theory1').textContent=(s*Math.sqrt(N)).toFixed(2);['n1','s1','w1'].forEach(id=>$(id+'Out').textContent=id==='s1'?+$('s1').value.toFixed(2):$(id).value)};['n1','s1','w1'].forEach(id=>$(id).oninput=draw1);$('reroll1').onclick=()=>{seed1++;draw1()};
// Task 2
let sim2={};function reset2(){sim2={t:0,bx:.5,by:.5,vx:0,vy:0,parts:[]};const n=+$('n2').value;for(let i=0;i<n;i++)sim2.parts.push({x:Math.random(),y:Math.random(),a:Math.random()*Math.PI*2,v:.006+Math.random()*.006});}function draw2(){const c=$('canvas2'),ctx=setupCanvas(c),w=c.clientWidth,h=c.clientHeight;clear(ctx,w,h);if(!sim2.parts.length)reset2();let kick=+$('kick2').value,ratio=+$('ratio2').value;sim2.t+=.016;sim2.parts.forEach(p=>{p.x+=Math.cos(p.a)*p.v;p.y+=Math.sin(p.a)*p.v;if(p.x<.03||p.x>.97){p.a=Math.PI-p.a;p.x=Math.max(.03,Math.min(.97,p.x))}if(p.y<.03||p.y>.97){p.a=-p.a;p.y=Math.max(.03,Math.min(.97,p.y))}let dx=p.x-sim2.bx,dy=p.y-sim2.by,d=Math.hypot(dx,dy);if(d<.035){let nx=dx/d||1,ny=dy/d||0;sim2.vx+=nx*ratio*0.002*kick;sim2.vy+=ny*ratio*0.002*kick;p.a=Math.atan2(-ny,-nx)}});sim2.bx+=sim2.vx;sim2.by+=sim2.vy;sim2.vx*=.997;sim2.vy*=.997;if(sim2.bx<.05||sim2.bx>.95)sim2.vx*=-1;if(sim2.by<.05||sim2.by>.95)sim2.vy*=-1;ctx.strokeStyle='#253038';ctx.strokeRect(18,18,w-36,h-36);sim2.parts.forEach(p=>{ctx.fillStyle='#6f7b82';ctx.beginPath();ctx.arc(18+p.x*(w-36),18+p.y*(h-36),2,0,7);ctx.fill()});ctx.fillStyle='#c8ff5a';ctx.shadowBlur=18;ctx.shadowColor='#c8ff5a';ctx.beginPath();ctx.arc(18+sim2.bx*(w-36),18+sim2.by*(h-36),8,0,7);ctx.fill();ctx.shadowBlur=0;$('speed2').textContent=(Math.hypot(sim2.vx,sim2.vy)*1000).toFixed(2);$('time2').textContent=sim2.t.toFixed(1)+' s';$('n2Out').textContent=$('n2').value;$('ratio2Out').textContent=(+$('ratio2').value).toFixed(2);$('kick2Out').textContent=(+$('kick2').value).toFixed(1);requestAnimationFrame(draw2)}$('run2').onclick=reset2;['n2','ratio2','kick2'].forEach(id=>$(id).oninput=()=>{if(id==='n2')reset2()});reset2();requestAnimationFrame(draw2);
// shared chart
function plot(ctx,fn,xmin,xmax,ymin,ymax,label,color='#c8ff5a'){const c=ctx.canvas,w=c.clientWidth,h=c.clientHeight;const pad={l:48,r:20,t:20,b:38};const X=x=>pad.l+(x-xmin)/(xmax-xmin)*(w-pad.l-pad.r),Y=y=>h-pad.b-(y-ymin)/(ymax-ymin)*(h-pad.t-pad.b);ctx.strokeStyle='#273039';ctx.strokeRect(pad.l,pad.t,w-pad.l-pad.r,h-pad.t-pad.b);ctx.beginPath();for(let i=0;i<500;i++){let x=xmin+(xmax-xmin)*i/499,y=fn(x);if(i)ctx.lineTo(X(x),Y(y));else ctx.moveTo(X(x),Y(y))}ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#68747a';ctx.font='10px DM Mono';ctx.fillText(label,pad.l,pad.t+12);return {X,Y}}
// Task 3
function planck(l,T){const h=6.62607015e-34,c=2.99792458e8,k=1.380649e-23,L=l*1e-9,x=h*c/(L*k*T);return 2*h*c*c/(L**5*Math.expm1(Math.min(x,700)))*1e-9}
function draw3(){const c=$('canvas3'),ctx=setupCanvas(c),w=c.clientWidth,h=c.clientHeight;clear(ctx,w,h);let T=+$('t3').value,win=+$('win3').value;let ymax=0;for(let i=1;i<=win;i+=10)ymax=Math.max(ymax,planck(i,T));let pad={l:52,r:20,t:28,b:42};ctx.strokeStyle='#273039';ctx.strokeRect(pad.l,pad.t,w-pad.l-pad.r,h-pad.t-pad.b);for(let [tt,col] of [[T,'#c8ff5a'],[Math.max(2500,T-1500),'#7ce6ff'],[Math.min(9000,T+1500),'#ffbf69']]){ctx.beginPath();for(let i=1;i<=win;i+=4){let x=pad.l+(i-1)/(win-1)*(w-pad.l-pad.r),y=h-pad.b-planck(i,tt)/ymax*(h-pad.t-pad.b);i===1?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle=col;ctx.lineWidth=2;ctx.stroke()}let peak=2.897771955e6/T;$('t3Out').textContent=T;$('win3Out').textContent=win;$('peak3').textContent=peak.toFixed(0)+' nm';ctx.fillStyle='#6c777c';ctx.font='10px DM Mono';ctx.fillText('wavelength / nm',w/2-35,h-12);ctx.fillText('relative spectral radiance',8,16)}['t3','win3'].forEach(id=>$(id).oninput=draw3);draw3();
// Task 4
const h=6.62607015e-34,e=1.602176634e-19,c0=2.99792458e8;function draw4(){const c=$('canvas4'),ctx=setupCanvas(c),w=c.clientWidth,hc=c.clientHeight;clear(ctx,w,hc);let phi=+$('metal4').value,f=+$('f4').value*1e14,th=phi*e/h;let fmax=2e15,ymax=Math.max(8,(h*fmax/e/1e0-2));let pad={l:55,r:20,t:25,b:42};ctx.strokeStyle='#273039';ctx.strokeRect(pad.l,pad.t,w-pad.l-pad.r,hc-pad.t-pad.b);ctx.beginPath();for(let i=0;i<500;i++){let x=4e14+(fmax-4e14)*i/499;let y=h*x/e-phi;if(x<th)continue;let X=pad.l+(x-4e14)/(fmax-4e14)*(w-pad.l-pad.r),Y=hc-pad.b-Math.max(0,y)/ymax*(hc-pad.t-pad.b);i===0||x<th+((fmax-4e14)/499)?ctx.moveTo(X,Y):ctx.lineTo(X,Y)}ctx.strokeStyle='#c8ff5a';ctx.lineWidth=2;ctx.stroke();let vs=h*f/e-phi;let f0=th;$('f4Out').textContent=(f/1e15).toFixed(2);$('threshold4').textContent=(f0/1e14).toFixed(2)+'×10¹⁴ Hz';$('vs4').textContent=vs>=0?vs.toFixed(2)+' V':'no emission';$('photoEq4').innerHTML=vs>=0?`hf = φ + K<sub>max</sub> → K<sub>max</sub> = ${vs.toFixed(2)} eV`:'hf < φ → no photoelectron';ctx.fillStyle='#6c777c';ctx.font='10px DM Mono';ctx.fillText('frequency / Hz',w/2-35,hc-12)}['metal4','f4'].forEach(id=>$(id).oninput=draw4);draw4();
// Task 5
function draw5(){let ni=+$('ni5').value,nf=Math.min(+$('nf5').value,ni-1);$('nf5').value=nf;$('ni5Out').textContent=ni;$('nf5Out').textContent=nf;let Ei=-13.605693/(ni*ni),Ef=-13.605693/(nf*nf),E=Ei-Ef,lam=1239.841984/E;$('e5').textContent=E.toFixed(3)+' eV';$('lambda5').textContent=lam.toFixed(1)+' nm';$('levels5').innerHTML=`n=${ni}: ${Ei.toFixed(3)} eV<br>n=${nf}: ${Ef.toFixed(3)} eV`;let c=$('canvas5'),ctx=setupCanvas(c),w=c.clientWidth,h=c.clientHeight;clear(ctx,w,h);let levels=[];for(let n=1;n<=7;n++)levels.push({n,E:-13.605693/n**2});let y=E=>h-45-(E+14)/(14)*(h-80);ctx.strokeStyle='#273039';levels.forEach(L=>{ctx.strokeStyle='#41505a';ctx.beginPath();ctx.moveTo(55,y(L.E));ctx.lineTo(w-55,y(L.E));ctx.stroke();ctx.fillStyle='#8a969b';ctx.font='10px DM Mono';ctx.fillText('n='+L.n,18,y(L.E)+3)});ctx.strokeStyle='#c8ff5a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(w/2,y(-13.605693/ni**2));ctx.lineTo(w/2,y(-13.605693/nf**2));ctx.stroke();ctx.fillStyle='#c8ff5a';ctx.font='11px DM Mono';ctx.fillText(`${ni} → ${nf} · ${lam.toFixed(1)} nm`,w/2+12,(y(-13.605693/ni**2)+y(-13.605693/nf**2))/2)}['ni5','nf5'].forEach(id=>$(id).oninput=draw5);draw5();
// Task 6
function draw6(){let V=+$('v6').value*1000,d=+$('d6').value*1e-9,lambda=h/Math.sqrt(2*9.1093837139e-31*e*V),c=$('canvas6'),ctx=setupCanvas(c),w=c.clientWidth,hc=c.clientHeight;clear(ctx,w,hc);ctx.strokeStyle='#43504a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(w/2,hc/2,Math.min(w,hc)*.39,0,7);ctx.stroke();let count=0;for(let n=1;n<100;n++){let s=n*lambda/(2*d);if(s>1)break;let phi=Math.asin(s),r=.39*Math.min(w,hc)*Math.sin(2*phi);ctx.beginPath();ctx.arc(w/2,hc/2,r,0,7);ctx.strokeStyle=n%2?'#c8ff5a':'#7ce6ff';ctx.globalAlpha=.78;ctx.stroke();count++}ctx.globalAlpha=1;$('v6Out').textContent=(V/1000).toFixed(1);$('lambda6').textContent=(lambda*1e9).toFixed(3)+' nm';$('rings6').textContent=count;ctx.fillStyle='#6c777c';ctx.font='10px DM Mono';ctx.fillText('phosphor screen · r = 65 mm',18,20)}['v6','d6'].forEach(id=>$(id).oninput=draw6);draw6();
// Task 7
function draw7(){let n=+$('n7').value,a=+$('a7').value*1e-9,m=9.1093837139e-31,hb=1.054571817e-34,E=n*n*Math.PI**2*hb**2/(2*m*a*a)/e;let unc=.5*Math.sqrt(n*n*Math.PI**2/3-2);$('n7Out').textContent=n;$('a7Out').textContent=(a*1e9).toFixed(2);$('energy7').textContent=E.toFixed(2)+' eV';$('unc7').textContent=unc.toFixed(3);let c=$('canvas7'),ctx=setupCanvas(c),w=c.clientWidth,h=c.clientHeight;clear(ctx,w,h);let pad={l:45,r:20,t:25,b:42};ctx.strokeStyle='#273039';ctx.strokeRect(pad.l,pad.t,w-pad.l-pad.r,h-pad.t-pad.b);ctx.beginPath();for(let i=0;i<=500;i++){let xx=i/500,yy=Math.sin(n*Math.PI*xx)**2,X=pad.l+xx*(w-pad.l-pad.r),Y=h-pad.b-yy*(h-pad.t-pad.b);i?ctx.lineTo(X,Y):ctx.moveTo(X,Y)}ctx.strokeStyle='#c8ff5a';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#6c777c';ctx.font='10px DM Mono';ctx.fillText('|ψₙ|²',12,25);ctx.fillText('x / a',w/2,h-12)}['n7','a7'].forEach(id=>$(id).oninput=draw7);draw7();
// Task 8
function draw8(){let th=+$('theta8').value*Math.PI/180,ph=+$('phi8').value*Math.PI/180,cl=1-Math.cos(th)**2*Math.cos(ph)**2-Math.sin(th)**2*Math.sin(ph)**2,qu=Math.sin(ph-th)**2;$('theta8Out').textContent=$('theta8').value;$('phi8Out').textContent=$('phi8').value;$('class8').textContent=cl.toFixed(3);$('quant8').textContent=qu.toFixed(3);$('diff8').textContent=`quantum − classical = ${(qu-cl).toFixed(3)}`;let c=$('canvas8'),ctx=setupCanvas(c),w=c.clientWidth,h=c.clientHeight;clear(ctx,w,h);let pad={l:50,r:20,t:25,b:40};ctx.strokeStyle='#273039';ctx.strokeRect(pad.l,pad.t,w-pad.l-pad.r,h-pad.t-pad.b);function curve(fn,col){ctx.beginPath();for(let i=0;i<=360;i++){let p=(-180+i)*Math.PI/180,y=fn(p),X=pad.l+i/360*(w-pad.l-pad.r),Y=h-pad.b-y*(h-pad.t-pad.b);i?ctx.lineTo(X,Y):ctx.moveTo(X,Y)}ctx.strokeStyle=col;ctx.lineWidth=2;ctx.stroke()}curve(p=>1-Math.cos(th)**2*Math.cos(p)**2-Math.sin(th)**2*Math.sin(p)**2,'#7ce6ff');curve(p=>Math.sin(p-th)**2,'#c8ff5a');ctx.fillStyle='#7d898e';ctx.font='10px DM Mono';ctx.fillText('Bob angle φ / degrees',w/2-45,h-12)}['theta8','phi8'].forEach(id=>$(id).oninput=draw8);draw8();
// Task 9
function compton(EkeV,deg){let E=EkeV*1000*e,theta=deg*Math.PI/180,mc2=9.1093837139e-31*c0*c0,alpha=E/mc2;let Escat=E/(1+alpha*(1-Math.cos(theta)));let p0=E/c0,ps=Escat/c0,px=p0-ps*Math.cos(theta),py=-ps*Math.sin(theta),pe=Math.hypot(px,py),K=E-Escat,gamma=1+K/mc2,v=c0*Math.sqrt(1-1/gamma**2),phi=Math.atan2(py,px);return {shift:(Escat?E/Escat-1:0),v,phi,Escat}}function draw9(){let E=+$('e9').value,deg=+$('theta9').value,r=compton(E,deg);$('e9Out').textContent=E;$('theta9Out').textContent=deg;$('shift9').textContent=(r.shift*100).toFixed(2)+'%';$('speed9').textContent=(r.v/c0).toFixed(3)+' c';$('recoil9').textContent=(r.phi*180/Math.PI).toFixed(1)+'°';$('escat9').textContent=(r.Escat/e/1000).toFixed(2)+' keV';let c=$('canvas9'),ctx=setupCanvas(c),w=c.clientWidth,h=c.clientHeight;clear(ctx,w,h);let pad={l:48,r:20,t:24,b:40};ctx.strokeStyle='#273039';ctx.strokeRect(pad.l,pad.t,w-pad.l-pad.r,h-pad.t-pad.b);ctx.beginPath();for(let i=0;i<=500;i++){let a=i/500*Math.PI,rr=compton(E,a*180/Math.PI),X=pad.l+i/500*(w-pad.l-pad.r),Y=h-pad.b-(rr.v/c0)*(h-pad.t-pad.b);i?ctx.lineTo(X,Y):ctx.moveTo(X,Y)}ctx.strokeStyle='#c8ff5a';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#7c878c';ctx.font='10px DM Mono';ctx.fillText('recoil speed / c',12,18);ctx.fillText('photon angle θ / degrees',w/2-55,h-12)}['e9','theta9'].forEach(id=>$(id).oninput=draw9);draw9();
// Task 10 controls valid n,l,m and swap atlas image family
function clampOrb(){let n=+$('n10').value,l=Math.min(+$('l10').value,n-1);$('l10').value=l;let m=Math.max(-l,Math.min(l,+$('m10').value));$('m10').value=m;$('n10Out').textContent=n;$('l10Out').textContent=l;$('m10Out').textContent=m;$('orbitalName').textContent=`${n}${l===0?'s':l===1?'p':l===2?'d':'f'}, m=${m}`;$('orbitalLabel').textContent=`Hydrogenic density family · n=${n}, l=${l}, m=${m}`;$('orbitalImg').src=l>=2?'Code/task10_hydrogenic_orbitals_3d.png':'Code/task10_hydrogenic_orbitals_2d.png'}['n10','l10','m10'].forEach(id=>$(id).oninput=clampOrb);clampOrb();
window.addEventListener('resize',()=>{draw1();draw3();draw4();draw5();draw6();draw7();draw8();draw9()});
